workflows:
    ios-workflow:
      name: iOS Workflow
      environment:
        vars:
          XCODE_WORKSPACE: "Perp.xcodeproj" # <-- Put the name of your workspace here.
          XCODE_SCHEME: "Perp" # <-- Put the name of your scheme here.
          BUNDLE_ID: "com.beauth.perpetual" # <-- Put your Bundle Id here.
          # https://docs.codemagic.io/code-signing-yaml/signing-ios/
          APP_STORE_CONNECT_ISSUER_ID: Encrypted(Z0FBQUFBQmhMNGR6SDgzVWtKSENJV1VNMC1jV3pzWWd2cDItbE5QX2M4andKX3N2R29pdkxTam5aeTM1MF9WV1lHV0NuZGlmUUcwcGZkaklqMGZlSzdPamg5S3ptakZLNkE9PQ==) # <-- Put your encrypted App Store Connect Issuer Id here 
          APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(Z0FBQUFBQmhMNGZVempSWm8zMkJrOF9XOVRoRnBZQTdBc3J1QmxWbnNJQzFjdWxJN0R0WGN5YUtxVVBNZ09FMW4wYXluWFNIbEFRRUgtRi1ybVR1UWVfYjFvWUZwRlAwUzRIQXVvaWdRdUpiYzhHa05oLXhoamR4YUNsSG5GTkV6Rkc0T1MxbEZaU3Q=) # <-- Put your encrypted App Store Connect Key Identifier here 
          APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhMNDhSbjQ1OFVMZmFlYzFWb2ZHSGpfa2JyVlY5d0ZzLTFSMElZOEpTZjFyU2NxN2FIa3dremo4aWNuNjJTVF9GTGtucWNjYlk2T1ZDQUpKQ2NZZDR5TDZWRndRMW13Vk0yd2lJSEJEZi05elVlOXhQblRtQ2xRZTZyU2lXeWRXVEx0OTBQV3dLXzBlOHpiZkVQZTh3Z1UxU1NSV1BmWnh1QWpSXy1EUUFhcVRfZGlQU0VyR0NxbC1vZGFTZFhxNEpPZkQ3b2tETlZmMGphQnhiNncxbzdETUJEcEVYYU1nVmI2N1VrX0xXZXpZYkFsUmEzdTFZYXJJMGpHUk9XVHFEa2hscGhuSzNYeVM3cFZpZHM5OEVzcW4xSkVyaGdDcGsycnI4ckJtY19ELVBvREI3dnhJOEJ5eWRiazljbkI0V0FKbEQycHA1Q19mLUtONkxRU3NURXJIWFNnPT0=) # <-- Put your encrypted App Store Connect Private Key here 
          CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmhMNDYzMnI5Wmh2YTN3VFNfZGhGc1FxUThxQy1IcGFBMWNENWVnQ1drUGZqc0pJT19SQUJnLW9mRm5tc19FRjV2Vm9Tb3BHWkc5SUVRMkRlbVJma0VhdlF4NHp1SDhQU1hVLUYtUHFLbU43R3ZISkNzd1Z2aTVXNndWc2hyOTdIY1J0dm1GSmZlNTh1LUFCMWtwY0E2T0M4R01oOEJ1a1JRa3JIWU5PVUd3TWdrQzl1cmZKT2c5RXJ1UDV5eUFxcW1EMHRyT0Q5cG1MTDU0Q2puUWo2cU8yXzhfaUNHQk5pTUJSZGs0RURXTTgyUTNIcEpNSnhaY1VUYUtEM1ZNMDhaOU0ySFRVZlZyZF9TcThqUk5rVmVHZlJ2R2p6UjdHcUFTQmptQzlaNlVXb1gydjZNT0hWMzctSlpjOGd1TUx6aHlybUJBRWpsTTNWSEFFQzFYM1E3bnlFWVozUEczZTY4SG92VmRFcU1LWmtKLWhQS2lsMXdkaDdRcWxST2VSRWEyTzNISEZucm1qODlPNHE3SUZUQkhnSFBIbElyajNBQzFfaWJ6WW56bGg3bHhlLWZNZnVQc05kZExaSjhMXzVqVEZuZFNVTzN3M0xURW9pVHNLajljaHhGcnoyeXBCYmRPR2hBdzE5dW5oa1dmTUtDOElQX2EtdHVON0xMckp0cjVjZ3hHX3FFUFJRYmZKc2VjRkRmdW81N3R0UHVPVnlIOFlWSmRjRHAzQjNEbUVhb0NLZEVmMUhnWm1LUG5zTGdVbGY0VTJqbzZaWWtBbGsyY05td0w0d0ZSZWRaS2IyaUprTVdTdnV5QkJwTzRUWkpDU2FHZzBLLWhXVGs1VlNHeUxHMXFQcG53aEFteVdVeHJpMzlBTTZoZm5vcjVRRWlNOXVtODYta0xNa0VMWTUxRFVlRTE4eVJjUGV0aVRRa2daeVFBajZseUF3cE9jbHd3aC1GVFhCMXEtWUUtT3lhcE1aejB1aFpVSnFqdkFnWVNUNVliRUVZQVRra2pYYnZwbFMzazdfdUVWRU1JOThTcUpxVnVFY0JHQUhsZXdBZjVtOUt0c0xpV3lRYU9jTU5qLUx5X3RkUV9WTFpTaDcwWFVhUzVyMVdvVmdvN0d2amxsUURDSGlrVXJzb215SHNLZzBrQVg2SVJ6ZFhxd1A2U3hQM08xRmcxVG9USk9xSldhcWU0dTlJOE1WazdlVi1MWFlWU2Q3Z0FlNHhBTkZDYWxmTHQ0cU5wVTFGcF9MWS05YjJKQ2NhdEVyWHpwcEwteUZGM1RpU1lBa2hmTGV1Y2UzNllhdDVTcjZfMmcxMmNnTFJfWkZKdEVTdlJnZkt0bHR5dW93dFR5akwtZU1oRTRmVTdicVpncW93LTZZVzAtTDZPZzd1T1ZXbHo3NHlxRExLdm9DT0tnTjBFRExwRDJ6bFJsTGNrOTRmMHhFM3I1VDVodXoxTzh5aGxKRVJvVmIySVB0OXB2M1lQOEhsSjkzZXNndDJaekJKU2NpdkZjbXFWRGdZSVc2cXJTWElmajhFcDFkbjVlVjNVS0V5MFBpdkFPeDlGZ0hYQjBJV1VjUE9YSV9UWUVmOEttYWFkdldjVjJGbk1sWlItc2JFb2JaVHZfN3hmNjkyQTBqdjdhX2hpUFFsSjN4eFdELXVTdGFNRXFGanhKeUppOE14eGtpWlI2OWlTdC1DaUpRRXhkajhGQWlXSjFPXzcwUXRWRW1NSjJfQzNlN0c0RjU2eVotUkFNa1NfZ01aZ0FEa3lVRFhXMkl1NUFUcUk3eU4tR25Gb2lvenBZYTJMd05Nelc3UjNNeV9zSzhKX0ZENWJnbW9SQnJKb2w5bzZoMmFxZlpDTUFwTm5JVGs2LXl1R1doVExvZnpkR2h4VDhZUjhWTDdSUkFEVG92Q2hlMjNqT3A2Q1JWMExEVGkwcXBhX0FKeUd6SmRPRkVsWjlUUGhrUi1NTzVvc2VZaFRGQUIzZGdYZV9xS1RYZ19CWVRfZWtSeER1eDEzYndGek1ieW5aMGNNaDQ5TkFZUGIyV1pMclhFSFA2YzdEUV9WNGlEZFd4UFl5R0w3cmJiVDd4NEhoRU5nRVFjQl9GQTFaN2hJUTNta0pXUUxXQWtZTjNxMlNwOHRDREk5aVkwcW5jNTVld3pWZW92WlpPR3M5TVJaWlViclZSeFpxeFZobTZwdmNiZ3ZIVXlPZUw0MFJ5SDhZdXZLcFBvMXl3ODdtQWcxNjZCSjJwcjhkS3dRWEF0S3FLQl9pZEhhaTRKa2VmN2pjMFVSdm00VHNyQmFMTk0wTUk4WVNRMzZLbTdPRG5yWW5pS1VaZExfMnI3Zk91LTFoMHZZcjBGSWlxdzc0WVRrOV90VEFXSkVMT0czNmtKV0ZhSUVsNmhzQ2ZIZUplUFB2UC03Zm5uNlRzX3lzWnctVXlDazJfcXNNOXhmOE9oMXBXeWI4SS1Xem5IUVlLamhoanZBQ0hEWnV5dlVBeWJWSFI1d09xM2J6MW1ibThPenhNeWxFNTNFMXhlZE91eHRfbjBiZ1NZQUlQR1ZpQkc4eGgxdE5kZFN1RUJKbFdZdUJuMGhxUUZyb0lUbnhHdU5LZWFHNzlLa3ZocjVab0FxM1Zza2pQOW1qbWRCNExyS0pTWTlqY2ZsZENfeEkzQ29xMFBmdmlSY3pyY3paOWxlaXNxSUtZVFc3N3phbFAzeWlab21GNmdhZmtrdHdjbmYtWndLdHJnWVJCWERpa1VXaUlTRGkxVXlRdGRELUNhWW1aS3pFUWR1T0h1Y0dfZ1gtTzBnTGhjU3pCOERjWFZOZVowcTNzNm5BZXdyVm5LV0JqTlVRS2RPNVR1RTBoaTJTbVRvUUhsdmJqVkRzTzlITGpPak5WSVo4ZFRiTVdiYlVWRGc1SmZkazJrYzRyZHZSa3pwRlV4dWp6ek1pTW82X19aWlJXME9hbXZlSlE9) # <-- Put your encrypted Certificate Private Key here 
          APP_STORE_APP_ID: 1583770606 # <-- Put the app id number here. This is found in App Store Connect > App > General > App Information
        xcode: latest
      triggering:
        events:
          - push
          # - tag
          - pull_request
        branch_patterns:
          - pattern: 'dev'
            include: true
            source: true
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Fetch signing files
          script: |
            app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: |
            xcode-project use-profiles
        - name: Increment build number
          script: |
            #!/bin/sh
            set -e
            set -x
            cd $FCI_BUILD_DIR
            # agvtool new-version -all $(($BUILD_NUMBER + 1))
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") + 1))
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
            key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such as $APP_STORE_CONNECT_ISSUER_ID
            submit_to_testflight: true                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
            beta_groups:                                    # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
                  - public
                  # - group name 2
        email:
            recipients:
              - spapinwar@gmail.com
            notify:
              success: true
              failure: true